export const cuisineList = [
    "Ethiopian",
    "Moroccan",
    "Nigerian",
    "South African",
    "Ghanaiae",
    "Kenyan",
    "Tunisian",
    // Asian Cuisines
    "Chinese",
    "Japanese",
    "Indian",
    "Thai",
    "Vietnamese",
    "Korean",
    "Malaysian",
    "Indonesian",
    "Filipino",
    "Sri Lankan",
    // European Cuisines
    "Italian",
    "French",
    "Spanish",
    "Greek",
    "German",
    "British",
    "Portuguese",
    "Russian",
    "Turkish",
    "Dutch",
    "American",
    "Mexican",
    "Canadian",
    "Cuban",
    "Jamaican",
    "Haitian", 
    // South American Cuisines
    "Brazilian",
    "Argentinian",
    "Peruvian",
    "Chilean",
    "Colombian",
    "Venezuelan",
    // Middle Eastern Cuisines
    "Lebanese",
    "Israeli",
    "Persian (Iranian)",
    "Syrian",
    "Iraqi",
    "Saudi Arabian",
    // Oceanian Cuisines
    "Australian",
    "New Zealand",
    "Fijian",
    "Samoan"
]